### ISSUE TITLE
Usage de sqla_map_name

### ISSUE THREAD

**Issue by ramabouda** [ouihelp/yesaide#3]
Je me demande à quoi sert concrètement le paramètre `sqla_map_name` dans le `MappingManagingWorker`. 

Dans `get` je constate que ça permet de passer un kwarg avec ce nom, mais à l'utilisation c'est équivalent à faire `get(sqla_obj=mon_objet)` `get(sqla_obj_id=mon_objet_id)`. 

Je n'ai pas trouvé d'autre endroit où il était appelé.

**Comment by b4stien** [comment]
Ça te permet effectivement de faire des `get(foo=bar)` ou `get(foo_id=bar.id)` là où sinon il faudrait faire des `get(sqla_obj=bar)` ou des `get(sqla_obj_id=bar.id)`.

Il s'agit de préciser quelle clef `MappingManagingWorker.get` va aller chercher dans les `kwargs` qui lui sont passés.

J'espère que ça aide.

**Comment by ramabouda** [comment]
Pourquoi n'utiliserait-on pas toujours les clés `sqla_obj` et `sqla_obj_id`, sans le mécanisme du choix du nom du kwarg?
Les avantages que je vois sont : 
* pas de magie : on a le même nom de kwarg pour tous les `MappingManagingWorker`, au lieu d'utiliser un nom de kwarg défini à l'instanciation du service
* simplification du fonctionnement interne de yesaide, il serait plus facile de suivre ce qu'il se passe
* simplification de l'instanciation d'un service : je ne pense pas qu'on puisse deviner à quoi sert ce paramètre quand on voit l'instanciation d'un service

Après ton explication, j'ai trouvé un usage dans `notification = self.get(notification=notification)`. C'est d'ailleurs moi qui l'ai écrit (sans doute avec ton aide ;) ), mais je ne comprenais pas ce qu'il se passait derrière, ce qui je pense est un bon indicateur que ce n'est pas très intuitif!
